// <auto-generated />
namespace DotNetBay.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201603302017053_FirstChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
